debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    # Mysql DB 접속
#    url: jdbc:mysql://localhost:3306/board
#    username: shin
#    password: thisisTESTpw!@#
#    driver-class-name: com.mysql.cj.jdbc.Driver

# h2 DB 접속
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
#  h2.console.enabled: true # H2 연결(테스트 용도로만 사용)
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
